from __future__ import annotations

from dataclasses import dataclass
from typing import Any
import json
import os
import smtplib
import ssl
from email.message import EmailMessage
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import yfinance as yf


st.set_page_config(
    page_title="Darvas + Minervini Crypto Scanner",
    page_icon="📦",
    layout="wide",
)


ALERT_STATE_FILE = Path(".breakout_alert_state.json")

CRYPTO_ASSETS = {
    "Bitcoin": "BTC-USD",
    "Ethereum": "ETH-USD",
}


@dataclass(frozen=True)
class Settings:
    history_period: str
    min_base_days: int
    max_base_days: int
    max_box_range_pct: float
    test_tolerance_pct: float
    minimum_high_tests: int
    minimum_low_tests: int
    breakout_buffer_pct: float
    breakout_volume_multiple: float
    dry_up_days: int
    baseline_volume_days: int
    dry_up_ratio_max: float
    atr_days: int
    near_high_pct: float
    chart_days: int




def load_alert_state() -> dict[str, str]:
    try:
        if ALERT_STATE_FILE.exists():
            data = json.loads(ALERT_STATE_FILE.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        pass
    return {}


def save_alert_state(state: dict[str, str]) -> None:
    try:
        ALERT_STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as exc:
        st.warning(f"Could not save alert history: {exc}")


def get_email_config() -> dict[str, Any]:
    """Read SMTP settings from Streamlit secrets or environment variables."""
    secret_email = {}
    try:
        secret_email = dict(st.secrets.get("email", {}))
    except Exception:
        secret_email = {}

    def value(name: str, default: Any = "") -> Any:
        return secret_email.get(name, os.getenv(f"BREAKOUT_{name.upper()}", default))

    return {
        "smtp_host": value("smtp_host", "smtp.gmail.com"),
        "smtp_port": int(value("smtp_port", 465)),
        "smtp_username": value("smtp_username"),
        "smtp_password": value("smtp_password"),
        "sender": value("sender") or value("smtp_username"),
        "recipient": value("recipient"),
        "use_ssl": str(value("use_ssl", "true")).lower() in {"1", "true", "yes", "on"},
    }


def email_configured(config: dict[str, Any]) -> bool:
    required = ["smtp_host", "smtp_port", "smtp_username", "smtp_password", "sender", "recipient"]
    return all(config.get(key) for key in required)


def send_breakout_email(
    config: dict[str, Any],
    asset_name: str,
    ticker: str,
    candle_date: str,
    box_result: dict[str, Any],
    strategy_score: int,
    test_only: bool = False,
) -> None:
    subject = (
        f"Test: breakout alerts configured for {asset_name}"
        if test_only
        else f"Confirmed breakout: {asset_name} ({ticker})"
    )
    if test_only:
        body = (
            f"Email alerts are configured correctly for the Darvas + Minervini scanner.\n\n"
            f"Asset currently selected: {asset_name} ({ticker})\n"
            f"Test generated by the Streamlit application."
        )
    else:
        body = f"""A confirmed Darvas breakout was detected.

Asset: {asset_name}
Ticker: {ticker}
Candle date: {candle_date}
Latest close: {format_currency(box_result['latest_close'])}
Box high: {format_currency(box_result['box_high'])}
Breakout level: {format_currency(box_result['breakout_level'])}
Breakout volume: {box_result['volume_multiple']:.2f}x average
Detected base length: {box_result.get('base_days', 0)} days
Base quality: {box_result.get('quality_score', 0):.1f}/100
Strategy score: {strategy_score}/100

The alert requires both a close above the configured breakout level and the configured volume confirmation.

Educational signal only; not investment advice.
"""

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = config["sender"]
    message["To"] = config["recipient"]
    message.set_content(body)

    if config["use_ssl"]:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL(config["smtp_host"], config["smtp_port"], context=context, timeout=30) as server:
            server.login(config["smtp_username"], config["smtp_password"])
            server.send_message(message)
    else:
        with smtplib.SMTP(config["smtp_host"], config["smtp_port"], timeout=30) as server:
            server.starttls(context=ssl.create_default_context())
            server.login(config["smtp_username"], config["smtp_password"])
            server.send_message(message)


def maybe_send_breakout_alert(
    enabled: bool,
    config: dict[str, Any],
    asset_name: str,
    ticker: str,
    candle_date: str,
    box_result: dict[str, Any],
    strategy_score: int,
) -> tuple[bool, str]:
    if not enabled:
        return False, "Email alerts are disabled."
    if not email_configured(config):
        return False, "Email settings are incomplete."
    if not box_result.get("confirmed_breakout", False):
        return False, "No confirmed breakout on the latest candle."

    alert_key = f"{ticker}:{candle_date}:{box_result['breakout_level']:.8f}"
    state = load_alert_state()
    if state.get(ticker) == alert_key:
        return False, "This breakout has already been emailed."

    send_breakout_email(
        config=config,
        asset_name=asset_name,
        ticker=ticker,
        candle_date=candle_date,
        box_result=box_result,
        strategy_score=strategy_score,
    )
    state[ticker] = alert_key
    save_alert_state(state)
    return True, f"Breakout alert sent to {config['recipient']}."


def safe_float(value: Any, default: float = np.nan) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


@st.cache_data(ttl=900, show_spinner=False)
def download_market_data(ticker: str, period: str) -> pd.DataFrame:
    """Download daily OHLCV data and normalize yfinance output."""
    data = yf.download(
        ticker,
        period=period,
        interval="1d",
        auto_adjust=False,
        progress=False,
        threads=False,
    )

    if data.empty:
        return pd.DataFrame()

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    required = ["Open", "High", "Low", "Close", "Volume"]
    missing = [column for column in required if column not in data.columns]
    if missing:
        raise ValueError(f"Missing columns from market data: {', '.join(missing)}")

    data = data[required].copy()
    data.index = pd.to_datetime(data.index).tz_localize(None)
    data = data.apply(pd.to_numeric, errors="coerce").dropna(subset=["Open", "High", "Low", "Close"])
    data["Volume"] = data["Volume"].fillna(0)
    return data


def add_indicators(data: pd.DataFrame, settings: Settings) -> pd.DataFrame:
    df = data.copy()

    for length in (20, 50, 150, 200):
        df[f"SMA_{length}"] = df["Close"].rolling(length).mean()

    prior_close = df["Close"].shift(1)
    true_range = pd.concat(
        [
            df["High"] - df["Low"],
            (df["High"] - prior_close).abs(),
            (df["Low"] - prior_close).abs(),
        ],
        axis=1,
    ).max(axis=1)

    df["TR"] = true_range
    df["ATR"] = true_range.rolling(settings.atr_days).mean()
    df["ATR_Pct"] = (df["ATR"] / df["Close"]) * 100

    df["Volume_Avg_20"] = df["Volume"].rolling(20).mean()
    df["Dollar_Volume"] = df["Close"] * df["Volume"]
    df["Dollar_Volume_Avg_20"] = df["Dollar_Volume"].rolling(20).mean()

    df["High_365"] = df["High"].rolling(365, min_periods=180).max()
    df["Low_365"] = df["Low"].rolling(365, min_periods=180).min()
    df["Distance_From_365D_High_Pct"] = ((df["High_365"] - df["Close"]) / df["High_365"]) * 100

    df["Return_30D_Pct"] = df["Close"].pct_change(30) * 100
    df["Return_90D_Pct"] = df["Close"].pct_change(90) * 100
    df["Return_180D_Pct"] = df["Close"].pct_change(180) * 100

    return df


def detect_current_box(df: pd.DataFrame, settings: Settings) -> dict[str, Any]:
    """Automatically identify the strongest active Darvas-style base.

    Candidate bases all end on the most recent completed candle. Their starting
    date varies from ``min_base_days`` to ``max_base_days``. Resistance and
    support are estimated from clusters of highs and lows, rather than from one
    isolated extreme candle. The latest candle is evaluated separately as the
    possible breakout candle.
    """
    minimum_required = settings.max_base_days + 2
    if len(df) < minimum_required:
        return {"valid": False, "reason": f"At least {minimum_required} candles are required"}

    completed = df.iloc[:-1].copy()
    latest = df.iloc[-1]
    previous = df.iloc[-2]
    tolerance = settings.test_tolerance_pct / 100
    candidates: list[dict[str, Any]] = []

    for base_days in range(settings.min_base_days, settings.max_base_days + 1):
        base = completed.tail(base_days).copy()
        if len(base) < base_days:
            continue

        # Use price clusters to keep a one-day wick from defining the box.
        upper_seed = safe_float(base["High"].quantile(0.85))
        lower_seed = safe_float(base["Low"].quantile(0.15))
        upper_cluster = base.loc[base["High"] >= upper_seed, "High"]
        lower_cluster = base.loc[base["Low"] <= lower_seed, "Low"]
        box_high = safe_float(upper_cluster.median())
        box_low = safe_float(lower_cluster.median())

        if not np.isfinite(box_high) or not np.isfinite(box_low) or box_high <= box_low:
            continue

        midpoint = (box_high + box_low) / 2
        range_pct = ((box_high - box_low) / midpoint) * 100
        high_tests = int((base["High"].sub(box_high).abs() / box_high <= tolerance).sum())
        low_tests = int((base["Low"].sub(box_low).abs() / box_low <= tolerance).sum())

        # Slight intraday excursions are allowed; closes should remain contained.
        close_tolerance = max(tolerance, 0.01)
        upper_close_limit = box_high * (1 + close_tolerance)
        lower_close_limit = box_low * (1 - close_tolerance)
        inside_ratio = float(
            ((base["Close"] <= upper_close_limit) & (base["Close"] >= lower_close_limit)).mean()
        )

        half = max(3, base_days // 2)
        early_atr = safe_float(base["ATR_Pct"].head(half).mean())
        late_atr = safe_float(base["ATR_Pct"].tail(half).mean())
        atr_contracting = bool(np.isfinite(early_atr) and np.isfinite(late_atr) and late_atr <= early_atr * 1.05)

        range_pass = range_pct <= settings.max_box_range_pct
        high_tests_pass = high_tests >= settings.minimum_high_tests
        low_tests_pass = low_tests >= settings.minimum_low_tests
        containment_pass = inside_ratio >= 0.90
        valid = all([range_pass, high_tests_pass, low_tests_pass, containment_pass])
        if not valid:
            continue

        # Prefer tight, well-tested, contained and volatility-contracting bases.
        tightness_score = max(0.0, 1 - range_pct / settings.max_box_range_pct)
        touch_score = min(1.0, (high_tests + low_tests) / 8)
        length_score = min(1.0, base_days / 40)
        quality_score = (
            35 * tightness_score
            + 25 * touch_score
            + 20 * inside_ratio
            + 10 * length_score
            + (10 if atr_contracting else 0)
        )

        candidates.append({
            "base": base,
            "base_days": base_days,
            "box_high": box_high,
            "box_low": box_low,
            "box_range_pct": range_pct,
            "high_tests": high_tests,
            "low_tests": low_tests,
            "inside_ratio": inside_ratio,
            "atr_contracting": atr_contracting,
            "quality_score": quality_score,
        })

    if not candidates:
        return {
            "valid": False,
            "state": "NO VALID BOX",
            "reason": "No qualifying base found within the automatic search range",
            "box_high": np.nan,
            "box_low": np.nan,
            "box_range_pct": np.nan,
            "high_tests": 0,
            "low_tests": 0,
            "inside_ratio": 0.0,
            "breakout_level": np.nan,
            "latest_close": safe_float(latest["Close"]),
            "previous_close": safe_float(previous["Close"]),
            "volume_multiple": np.nan,
            "price_breakout": False,
            "volume_breakout": False,
            "confirmed_breakout": False,
            "base_days": 0,
            "quality_score": 0.0,
            "checks": {},
        }

    # A small preference for the most recent/tighter nested base is already
    # captured by tightness; quality decides among all natural base lengths.
    winner = max(candidates, key=lambda item: item["quality_score"])
    base = winner["base"]
    box_high = winner["box_high"]
    box_low = winner["box_low"]
    breakout_level = box_high * (1 + settings.breakout_buffer_pct / 100)
    near_breakout_floor = box_high * 0.98

    latest_close = safe_float(latest["Close"])
    previous_close = safe_float(previous["Close"])
    latest_volume = safe_float(latest["Volume"], 0.0)
    average_volume = safe_float(df["Volume"].iloc[-21:-1].mean(), 0.0)
    volume_multiple = latest_volume / average_volume if average_volume > 0 else np.nan

    price_breakout = latest_close > breakout_level and previous_close <= breakout_level
    volume_breakout = volume_multiple >= settings.breakout_volume_multiple
    confirmed_breakout = price_breakout and volume_breakout
    price_only_breakout = price_breakout and not volume_breakout
    breakout_watch = not price_breakout and latest_close >= near_breakout_floor

    if confirmed_breakout:
        state = "CONFIRMED BREAKOUT"
    elif price_only_breakout:
        state = "PRICE BREAKOUT / WEAK VOLUME"
    elif breakout_watch:
        state = "BREAKOUT WATCH"
    else:
        state = "BUILDING A BOX"

    return {
        "valid": True,
        "state": state,
        "box_high": box_high,
        "box_low": box_low,
        "box_range_pct": winner["box_range_pct"],
        "high_tests": winner["high_tests"],
        "low_tests": winner["low_tests"],
        "inside_ratio": winner["inside_ratio"],
        "breakout_level": breakout_level,
        "latest_close": latest_close,
        "previous_close": previous_close,
        "volume_multiple": volume_multiple,
        "price_breakout": price_breakout,
        "volume_breakout": volume_breakout,
        "confirmed_breakout": confirmed_breakout,
        "box_start": base.index[0],
        "box_end": base.index[-1],
        "base_days": winner["base_days"],
        "quality_score": winner["quality_score"],
        "atr_contracting": winner["atr_contracting"],
        "candidate_count": len(candidates),
        "checks": {
            "Range within limit": True,
            "Enough upper-bound tests": True,
            "Enough lower-bound tests": True,
            "At least 90% closes contained": True,
            "ATR stable or contracting": winner["atr_contracting"],
        },
    }

def evaluate_trend_template(df: pd.DataFrame, settings: Settings) -> dict[str, Any]:
    latest = df.iloc[-1]

    close = safe_float(latest["Close"])
    sma_50 = safe_float(latest["SMA_50"])
    sma_150 = safe_float(latest["SMA_150"])
    sma_200 = safe_float(latest["SMA_200"])
    high_365 = safe_float(latest["High_365"])
    low_365 = safe_float(latest["Low_365"])

    sma_200_20_days_ago = safe_float(df["SMA_200"].iloc[-21]) if len(df) >= 221 else np.nan
    midpoint_365 = (high_365 + low_365) / 2 if np.isfinite(high_365) and np.isfinite(low_365) else np.nan
    distance_from_high = ((high_365 - close) / high_365) * 100 if high_365 else np.nan

    checks = {
        "Price above 50-day SMA": close > sma_50,
        "Price above 150-day SMA": close > sma_150,
        "Price above 200-day SMA": close > sma_200,
        "50-day SMA above 150-day SMA": sma_50 > sma_150,
        "150-day SMA above 200-day SMA": sma_150 > sma_200,
        "200-day SMA rising": sma_200 > sma_200_20_days_ago,
        "Price above 365-day midpoint": close > midpoint_365,
        f"Within {settings.near_high_pct:.0f}% of 365-day high": distance_from_high <= settings.near_high_pct,
    }

    passed = sum(bool(value) for value in checks.values())
    return {
        "checks": checks,
        "passed": passed,
        "total": len(checks),
        "pass_pct": passed / len(checks) * 100,
        "distance_from_high_pct": distance_from_high,
        "sma_50": sma_50,
        "sma_150": sma_150,
        "sma_200": sma_200,
    }


def evaluate_volume_dry_up(df: pd.DataFrame, settings: Settings) -> dict[str, Any]:
    if len(df) < settings.baseline_volume_days + settings.dry_up_days + 2:
        return {"pass": False, "ratio": np.nan}

    # Exclude the latest candle because it might be the breakout candle.
    completed = df.iloc[:-1]
    recent = completed["Dollar_Volume"].tail(settings.dry_up_days)
    baseline_end = len(completed) - settings.dry_up_days
    baseline_start = max(0, baseline_end - settings.baseline_volume_days)
    baseline = completed["Dollar_Volume"].iloc[baseline_start:baseline_end]

    recent_average = safe_float(recent.mean())
    baseline_average = safe_float(baseline.mean())
    ratio = recent_average / baseline_average if baseline_average > 0 else np.nan

    recent_atr = safe_float(completed["ATR_Pct"].tail(settings.dry_up_days).mean())
    prior_atr = safe_float(
        completed["ATR_Pct"].iloc[baseline_start:baseline_end].mean()
    )
    atr_contracting = recent_atr < prior_atr if np.isfinite(prior_atr) else False

    return {
        "pass": bool(ratio <= settings.dry_up_ratio_max and atr_contracting),
        "ratio": ratio,
        "recent_average": recent_average,
        "baseline_average": baseline_average,
        "recent_atr_pct": recent_atr,
        "prior_atr_pct": prior_atr,
        "atr_contracting": atr_contracting,
    }


def evaluate_relative_strength(
    asset_ticker: str,
    asset_df: pd.DataFrame,
    btc_df: pd.DataFrame,
) -> dict[str, Any]:
    if asset_ticker == "BTC-USD":
        returns = {
            "30-day return positive": safe_float(asset_df["Return_30D_Pct"].iloc[-1]) > 0,
            "90-day return positive": safe_float(asset_df["Return_90D_Pct"].iloc[-1]) > 0,
            "180-day return positive": safe_float(asset_df["Return_180D_Pct"].iloc[-1]) > 0,
        }
        passed = sum(returns.values())
        return {
            "label": "BTC momentum",
            "checks": returns,
            "passed": passed,
            "total": len(returns),
            "ratio_series": None,
            "latest_ratio": np.nan,
        }

    aligned = pd.concat(
        [
            asset_df["Close"].rename("Asset"),
            btc_df["Close"].rename("BTC"),
        ],
        axis=1,
        join="inner",
    ).dropna()

    aligned["ETH_BTC"] = aligned["Asset"] / aligned["BTC"]
    aligned["SMA_50"] = aligned["ETH_BTC"].rolling(50).mean()
    aligned["SMA_200"] = aligned["ETH_BTC"].rolling(200).mean()
    aligned["Return_30D"] = aligned["ETH_BTC"].pct_change(30) * 100
    aligned["Return_90D"] = aligned["ETH_BTC"].pct_change(90) * 100

    latest = aligned.iloc[-1]
    checks = {
        "ETH/BTC above 50-day average": latest["ETH_BTC"] > latest["SMA_50"],
        "ETH/BTC above 200-day average": latest["ETH_BTC"] > latest["SMA_200"],
        "ETH/BTC 30-day return positive": latest["Return_30D"] > 0,
        "ETH/BTC 90-day return positive": latest["Return_90D"] > 0,
    }

    passed = sum(bool(value) for value in checks.values())
    return {
        "label": "ETH relative strength vs BTC",
        "checks": checks,
        "passed": passed,
        "total": len(checks),
        "ratio_series": aligned,
        "latest_ratio": safe_float(latest["ETH_BTC"]),
    }


def calculate_score(
    box_result: dict[str, Any],
    trend_result: dict[str, Any],
    dry_up_result: dict[str, Any],
    rs_result: dict[str, Any],
) -> dict[str, Any]:
    box_points = 25 if box_result["valid"] else 0
    trend_points = round(30 * trend_result["passed"] / trend_result["total"])
    dry_up_points = 15 if dry_up_result["pass"] else 0
    rs_points = round(15 * rs_result["passed"] / rs_result["total"])

    breakout_points = 0
    if box_result["confirmed_breakout"]:
        breakout_points = 15
    elif box_result["price_breakout"]:
        breakout_points = 8
    elif box_result["state"] == "BREAKOUT WATCH":
        breakout_points = 4

    total = box_points + trend_points + dry_up_points + rs_points + breakout_points

    return {
        "Box": box_points,
        "Trend": trend_points,
        "Dry-up": dry_up_points,
        "Relative strength": rs_points,
        "Breakout": breakout_points,
        "Total": total,
    }


def make_price_chart(
    df: pd.DataFrame,
    box_result: dict[str, Any],
    settings: Settings,
    asset_name: str,
) -> go.Figure:
    visible = df.tail(settings.chart_days).copy()

    fig = go.Figure()
    fig.add_trace(
        go.Candlestick(
            x=visible.index,
            open=visible["Open"],
            high=visible["High"],
            low=visible["Low"],
            close=visible["Close"],
            name=asset_name,
        )
    )

    for length in (50, 150, 200):
        fig.add_trace(
            go.Scatter(
                x=visible.index,
                y=visible[f"SMA_{length}"],
                mode="lines",
                name=f"{length}-day SMA",
                line={"width": 1.2},
            )
        )

    if box_result.get("box_start") in visible.index or box_result.get("box_end") in visible.index:
        box_start = max(box_result["box_start"], visible.index.min())
        fig.add_shape(
            type="rect",
            x0=box_start,
            x1=visible.index.max(),
            y0=box_result["box_low"],
            y1=box_result["box_high"],
            line={"width": 1.5, "dash": "dash"},
            fillcolor="rgba(120,120,120,0.10)",
        )
        fig.add_hline(
            y=box_result["breakout_level"],
            line_dash="dot",
            annotation_text="Breakout level",
        )

    fig.update_layout(
        title=f"{asset_name}: Price, Trend Averages and Current Darvas Box",
        xaxis_title=None,
        yaxis_title="USD",
        xaxis_rangeslider_visible=False,
        height=650,
        legend={"orientation": "h"},
        margin={"l": 20, "r": 20, "t": 70, "b": 20},
    )
    return fig


def make_volume_chart(df: pd.DataFrame, settings: Settings) -> go.Figure:
    visible = df.tail(settings.chart_days).copy()

    fig = go.Figure()
    fig.add_trace(
        go.Bar(
            x=visible.index,
            y=visible["Dollar_Volume"],
            name="Daily USD volume",
        )
    )
    fig.add_trace(
        go.Scatter(
            x=visible.index,
            y=visible["Dollar_Volume_Avg_20"],
            mode="lines",
            name="20-day average USD volume",
        )
    )
    fig.update_layout(
        title="Dollar Volume",
        xaxis_title=None,
        yaxis_title="USD",
        height=380,
        legend={"orientation": "h"},
        margin={"l": 20, "r": 20, "t": 60, "b": 20},
    )
    return fig


def render_checks(title: str, checks: dict[str, bool]) -> None:
    st.subheader(title)
    for label, passed in checks.items():
        st.write(f"{'✅' if passed else '❌'} {label}")


def format_currency(value: float) -> str:
    if not np.isfinite(value):
        return "N/A"
    if abs(value) >= 1_000:
        return f"${value:,.2f}"
    return f"${value:,.4f}"


def main() -> None:
    st.title("📦 Darvas + Minervini Crypto Scanner")
    st.caption(
        "A present-state BTC/ETH scanner. It identifies boxes, trend quality, "
        "volume contraction and breakout conditions; it does not backtest or predict returns."
    )

    with st.sidebar:
        st.header("Asset")
        asset_name = st.selectbox("Cryptocurrency", list(CRYPTO_ASSETS))
        ticker = CRYPTO_ASSETS[asset_name]

        st.header("Darvas Box")
        min_base_days = st.slider("Minimum base length", 10, 40, 15)
        max_base_days = st.slider("Maximum base length", 30, 150, 90)
        max_box_range_pct = st.slider("Maximum box range (%)", 3.0, 35.0, 15.0, 0.5)
        test_tolerance_pct = st.slider("Boundary test tolerance (%)", 0.25, 5.0, 1.5, 0.25)
        minimum_high_tests = st.slider("Minimum upper-bound tests", 1, 6, 2)
        minimum_low_tests = st.slider("Minimum lower-bound tests", 1, 6, 2)

        st.header("Breakout")
        breakout_buffer_pct = st.slider("Breakout buffer (%)", 0.0, 5.0, 0.5, 0.1)
        breakout_volume_multiple = st.slider(
            "Minimum volume multiple", 1.0, 5.0, 1.5, 0.1
        )

        st.header("Volume Dry-Up")
        dry_up_days = st.slider("Recent dry-up days", 3, 30, 10)
        baseline_volume_days = st.slider("Baseline volume days", 10, 90, 30)
        dry_up_ratio_max = st.slider(
            "Maximum recent/baseline volume ratio", 0.25, 1.0, 0.70, 0.05
        )

        st.header("Trend")
        near_high_pct = st.slider("Maximum distance from 365-day high (%)", 5, 50, 25)
        atr_days = st.slider("ATR period", 5, 30, 14)
        chart_days = st.slider("Chart history days", 90, 730, 365, 30)

        st.header("Email Alerts")
        email_alerts_enabled = st.toggle("Send confirmed-breakout emails", value=False)
        email_config = get_email_config()
        if email_configured(email_config):
            st.success(f"SMTP configured for {email_config['recipient']}")
            if st.button("Send test email", use_container_width=True):
                try:
                    send_breakout_email(
                        email_config, asset_name, ticker, "test",
                        {"latest_close": np.nan, "box_high": np.nan, "breakout_level": np.nan,
                         "volume_multiple": np.nan, "base_days": 0, "quality_score": 0},
                        0, test_only=True,
                    )
                    st.success("Test email sent.")
                except Exception as exc:
                    st.error(f"Test email failed: {exc}")
        else:
            st.caption("Configure SMTP credentials in .streamlit/secrets.toml before enabling alerts.")

        refresh = st.button("Refresh market data", use_container_width=True)
        if refresh:
            st.cache_data.clear()

    settings = Settings(
        history_period="3y",
        min_base_days=min_base_days,
        max_base_days=max_base_days,
        max_box_range_pct=max_box_range_pct,
        test_tolerance_pct=test_tolerance_pct,
        minimum_high_tests=minimum_high_tests,
        minimum_low_tests=minimum_low_tests,
        breakout_buffer_pct=breakout_buffer_pct,
        breakout_volume_multiple=breakout_volume_multiple,
        dry_up_days=dry_up_days,
        baseline_volume_days=baseline_volume_days,
        dry_up_ratio_max=dry_up_ratio_max,
        atr_days=atr_days,
        near_high_pct=near_high_pct,
        chart_days=chart_days,
    )

    try:
        with st.spinner(f"Loading {asset_name} daily candles..."):
            raw_asset = download_market_data(ticker, settings.history_period)
            raw_btc = (
                raw_asset.copy()
                if ticker == "BTC-USD"
                else download_market_data("BTC-USD", settings.history_period)
            )
    except Exception as exc:
        st.error(f"Could not load market data: {exc}")
        st.stop()

    if raw_asset.empty or raw_btc.empty:
        st.error("No market data was returned. Try Refresh market data.")
        st.stop()

    asset_df = add_indicators(raw_asset, settings)
    btc_df = add_indicators(raw_btc, settings)

    minimum_rows = max(221, settings.max_base_days + 2)
    if len(asset_df) < minimum_rows:
        st.error(f"At least {minimum_rows} daily candles are required.")
        st.stop()

    box_result = detect_current_box(asset_df, settings)
    trend_result = evaluate_trend_template(asset_df, settings)
    dry_up_result = evaluate_volume_dry_up(asset_df, settings)
    rs_result = evaluate_relative_strength(ticker, asset_df, btc_df)
    score = calculate_score(box_result, trend_result, dry_up_result, rs_result)

    latest = asset_df.iloc[-1]
    prior = asset_df.iloc[-2]
    daily_change = (latest["Close"] / prior["Close"] - 1) * 100
    latest_date = asset_df.index[-1].strftime("%Y-%m-%d")

    try:
        alert_sent, alert_message = maybe_send_breakout_alert(
            enabled=email_alerts_enabled,
            config=email_config,
            asset_name=asset_name,
            ticker=ticker,
            candle_date=latest_date,
            box_result=box_result,
            strategy_score=score["Total"],
        )
        if alert_sent:
            st.success(alert_message)
    except Exception as exc:
        st.error(f"Breakout detected, but email delivery failed: {exc}")

    st.info(
        f"Latest available daily candle: **{latest_date}**. "
        "Crypto daily candles from the data source may still be incomplete before the UTC day closes."
    )

    metric_columns = st.columns(6)
    metric_columns[0].metric("Price", format_currency(latest["Close"]), f"{daily_change:.2f}%")
    metric_columns[1].metric("Strategy Score", f"{score['Total']}/100")
    metric_columns[2].metric("State", box_result["state"])
    metric_columns[3].metric("Box High", format_currency(box_result["box_high"]))
    metric_columns[4].metric("Box Low", format_currency(box_result["box_low"]))
    metric_columns[5].metric(
        "Breakout Volume",
        f"{box_result['volume_multiple']:.2f}×"
        if np.isfinite(box_result["volume_multiple"])
        else "N/A",
    )

    tabs = st.tabs(
        [
            "Overview",
            "Darvas Box",
            "Trend Template",
            "Volume Dry-Up",
            "Relative Strength",
            "Raw Data",
        ]
    )

    with tabs[0]:
        st.plotly_chart(
            make_price_chart(asset_df, box_result, settings, asset_name),
            use_container_width=True,
        )
        st.plotly_chart(
            make_volume_chart(asset_df, settings),
            use_container_width=True,
        )

        st.subheader("Score Breakdown")
        score_table = pd.DataFrame(
            [{"Component": key, "Points": value} for key, value in score.items() if key != "Total"]
        )
        st.dataframe(score_table, hide_index=True, use_container_width=True)

        if box_result["confirmed_breakout"]:
            st.success(
                "The latest candle meets the configured box, price-breakout and volume-confirmation rules."
            )
        elif box_result["state"] == "PRICE BREAKOUT / WEAK VOLUME":
            st.warning(
                "Price has cleared the breakout level, but volume has not reached the configured confirmation multiple."
            )
        elif box_result["state"] == "BREAKOUT WATCH":
            st.warning("Price is within 2% of the current box high.")
        elif box_result["valid"]:
            st.info("A valid box is present, but price is not yet near a confirmed breakout.")
        else:
            st.error("The selected lookback does not currently form a valid Darvas box.")

    with tabs[1]:
        details = {
            "Status": box_result["state"],
            "Detected base length": f"{box_result.get('base_days', 0)} days",
            "Base quality": f"{box_result.get('quality_score', 0):.1f}/100",
            "Box start": box_result["box_start"].strftime("%Y-%m-%d"),
            "Box end": box_result["box_end"].strftime("%Y-%m-%d"),
            "Box high": format_currency(box_result["box_high"]),
            "Box low": format_currency(box_result["box_low"]),
            "Box range": f"{box_result['box_range_pct']:.2f}%",
            "Upper-bound tests": box_result["high_tests"],
            "Lower-bound tests": box_result["low_tests"],
            "Closes contained": f"{box_result['inside_ratio'] * 100:.1f}%",
            "Breakout level": format_currency(box_result["breakout_level"]),
            "Price breakout": "Yes" if box_result["price_breakout"] else "No",
            "Volume confirmation": "Yes" if box_result["volume_breakout"] else "No",
        }
        st.dataframe(
            pd.DataFrame(details.items(), columns=["Measure", "Value"]),
            hide_index=True,
            use_container_width=True,
        )
        render_checks("Box Qualification", box_result["checks"])

    with tabs[2]:
        left, right = st.columns([1, 1])
        with left:
            render_checks(
                f"Trend Rules: {trend_result['passed']}/{trend_result['total']} Passed",
                trend_result["checks"],
            )
        with right:
            trend_values = pd.DataFrame(
                [
                    {"Measure": "50-day SMA", "Value": format_currency(trend_result["sma_50"])},
                    {"Measure": "150-day SMA", "Value": format_currency(trend_result["sma_150"])},
                    {"Measure": "200-day SMA", "Value": format_currency(trend_result["sma_200"])},
                    {
                        "Measure": "Distance from 365-day high",
                        "Value": f"{trend_result['distance_from_high_pct']:.2f}%",
                    },
                ]
            )
            st.dataframe(trend_values, hide_index=True, use_container_width=True)

    with tabs[3]:
        dryup_values = pd.DataFrame(
            [
                {
                    "Measure": "Recent/baseline dollar-volume ratio",
                    "Value": (
                        f"{dry_up_result['ratio']:.2f}"
                        if np.isfinite(dry_up_result["ratio"])
                        else "N/A"
                    ),
                },
                {
                    "Measure": "Recent average dollar volume",
                    "Value": format_currency(dry_up_result.get("recent_average", np.nan)),
                },
                {
                    "Measure": "Baseline average dollar volume",
                    "Value": format_currency(dry_up_result.get("baseline_average", np.nan)),
                },
                {
                    "Measure": "Recent average ATR %",
                    "Value": f"{dry_up_result.get('recent_atr_pct', np.nan):.2f}%",
                },
                {
                    "Measure": "Prior average ATR %",
                    "Value": f"{dry_up_result.get('prior_atr_pct', np.nan):.2f}%",
                },
                {
                    "Measure": "Volume + ATR dry-up passes",
                    "Value": "Yes" if dry_up_result["pass"] else "No",
                },
            ]
        )
        st.dataframe(dryup_values, hide_index=True, use_container_width=True)
        st.caption(
            "Dollar volume is used instead of raw coin volume so BTC and ETH activity is easier to compare."
        )

    with tabs[4]:
        render_checks(
            f"{rs_result['label']}: {rs_result['passed']}/{rs_result['total']} Passed",
            rs_result["checks"],
        )

        if rs_result["ratio_series"] is not None:
            ratio = rs_result["ratio_series"].tail(settings.chart_days)
            fig = go.Figure()
            fig.add_trace(
                go.Scatter(
                    x=ratio.index,
                    y=ratio["ETH_BTC"],
                    mode="lines",
                    name="ETH/BTC",
                )
            )
            fig.add_trace(
                go.Scatter(
                    x=ratio.index,
                    y=ratio["SMA_50"],
                    mode="lines",
                    name="50-day average",
                )
            )
            fig.add_trace(
                go.Scatter(
                    x=ratio.index,
                    y=ratio["SMA_200"],
                    mode="lines",
                    name="200-day average",
                )
            )
            fig.update_layout(
                title="Ethereum Relative Strength Versus Bitcoin",
                height=450,
                yaxis_title="ETH/BTC ratio",
                legend={"orientation": "h"},
            )
            st.plotly_chart(fig, use_container_width=True)

    with tabs[5]:
        display_columns = [
            "Open",
            "High",
            "Low",
            "Close",
            "Volume",
            "Dollar_Volume",
            "SMA_50",
            "SMA_150",
            "SMA_200",
            "ATR_Pct",
            "Distance_From_365D_High_Pct",
        ]
        export = asset_df[display_columns].copy().sort_index(ascending=False)
        st.dataframe(export, use_container_width=True)
        st.download_button(
            "Download analyzed CSV",
            data=export.to_csv().encode("utf-8"),
            file_name=f"{ticker.replace('-', '_')}_darvas_minervini.csv",
            mime="text/csv",
        )

    with st.expander("How the crypto adaptation works"):
        st.markdown(
            """
            - **Dynamic Darvas component:** The app searches every candidate base between the configured
              minimum and maximum lengths, then selects the strongest current structure. Resistance and
              support come from clusters of highs and lows, so a single wick does not define the box.
            - **Breakout:** The latest close must exceed the prior box high plus a buffer.
              Volume confirmation compares the latest coin volume with the previous 20 completed days.
            - **Minervini-style trend template:** Uses 50-, 150- and 200-day averages, a rising
              200-day average, the 365-day range midpoint and distance from the 365-day high.
            - **Volume dry-up:** Compares recent average USD trading volume with an earlier baseline
              and also requires average ATR percentage to contract.
            - **Relative strength:** Ethereum is evaluated against Bitcoin through ETH/BTC.
              Bitcoin uses positive 30-, 90- and 180-day momentum because it is the benchmark asset.
            """
        )

    with st.expander("Email alert setup"):
        st.markdown(
            """
Create `.streamlit/secrets.toml` beside `app.py`:

```toml
[email]
smtp_host = "smtp.gmail.com"
smtp_port = 465
smtp_username = "your-email@gmail.com"
smtp_password = "your-app-password"
sender = "your-email@gmail.com"
recipient = "destination@example.com"
use_ssl = true
```

For Gmail, use an **App Password**, not your normal account password. The scanner sends only once for each unique ticker, candle date and breakout level. A deployed Streamlit app must rerun periodically for automatic checking; otherwise alerts are evaluated when the page is opened or refreshed.
            """
        )

    st.caption(
        "Educational scanner only—not investment advice. Signals can fail, volume data varies by source, "
        "and the current UTC daily candle may be incomplete."
    )


if __name__ == "__main__":
    main()
